# Generated by Django 5.0.6 on 2024-06-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_subscription_updated_at_alter_category_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(choices=[('Mesa', 'Mesa'), ('Silla', 'Silla'), ('Cama', 'Cama'), ('Comedor', 'Comedor'), ('Jardín', 'Jardín'), ('Escritorio', 'Escritorio')], default='Cama', help_text='(silla, mesa...)'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
